In [1]:
# keras pytorch tensorflow are popular choices for deep learning frameworks

#Pytorch is an open source machine learning and deep learning library developed by facebook. It gives a faster alternative / replacement to numpy by providing 

In [2]:
import torch

a=torch.tensor([[0.1,0.2],[0.3,0.4],[3,4]])
a.shape

torch.Size([3, 2])

In [8]:
c=torch.tensor([[[2],[3]],[[4],[5]]])
c.shape


torch.Size([2, 2, 1])

In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
tensor_a=torch.from_numpy(a)
tensor_a

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
a=torch.tensor([[1,2],[3,4]],dtype=torch.float16)
a

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)

In [14]:
r=torch.rand(2,2,2)
r

tensor([[[0.5810, 0.2102],
         [0.5675, 0.3413]],

        [[0.3645, 0.1313],
         [0.9184, 0.6560]]])

In [17]:
zeros=torch.zeros(2,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [18]:
ones=torch.ones(2,2,3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [19]:
ones.shape

torch.Size([2, 2, 3])

In [22]:
f=torch.full((3,2),0.5)
f.shape

torch.Size([3, 2])

In [23]:
lin=torch.linspace(0,20,steps=5)

In [25]:
lin.shape

torch.Size([5])

In [26]:
log=torch.logspace(-3,3,steps=4)
log

tensor([1.0000e-03, 1.0000e-01, 1.0000e+01, 1.0000e+03])

In [29]:
a=torch.tensor([[0.5,0.5],[0.5,0.5]])
b=torch.zeros_like(a)
b

c=torch.ones_like(a)
c

tensor([[1., 1.],
        [1., 1.]])

In [30]:
i=torch.tensor([[1,2],[3,4]],dtype=torch.int)
i



tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [31]:
a=torch.arange(1,10,step=2)
a

tensor([1, 3, 5, 7, 9])

In [33]:

r=torch.randperm(10)
r

tensor([3, 0, 1, 5, 8, 2, 7, 6, 9, 4])

In [34]:
a=torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [36]:
a[1][1]

tensor(4)

In [39]:
a=torch.tensor([[[0.42]]])

In [41]:
a.shape

torch.Size([1, 1, 1])

In [42]:
a.item()

0.41999998688697815

In [43]:
a=torch.zeros(10)
a

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
a.shape

torch.Size([10])

In [51]:
b=a.view(2,5)
b

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [52]:
a


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
c=torch.cat([a,a,a],1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [59]:
c

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])

In [57]:
b.shape

torch.Size([30])

In [63]:
a=torch.zeros(2,1)

In [64]:
a

tensor([[0.],
        [0.]])

In [71]:
b=torch.stack([a,a,a],1)

In [72]:
b

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])

In [91]:
a=torch.FloatTensor([[1,2,5],[5,5,6],[7,8,9]])
a

tensor([[1., 2., 5.],
        [5., 5., 6.],
        [7., 8., 9.]])

In [92]:
index=torch.LongTensor([0,1])

In [93]:
index

tensor([0, 1])

In [94]:
b=torch.index_select(a,1,index)

In [88]:
b

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

In [97]:
a=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
a                       

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [98]:
mask=torch.ByteTensor([[0,1,0],[1,1,1],[0,1,0]])
mask

tensor([[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [103]:
mask.shape

torch.Size([3, 3])

In [100]:
a.shape

torch.Size([3, 3])

In [114]:
l=torch.masked_select(a,mask)
l

tensor([2., 4., 5., 6., 8.])

In [112]:
mask=mask.bool()
mask

tensor([[False,  True, False],
        [ True,  True,  True],
        [False,  True, False]])

In [116]:
l.shape

torch.Size([5])

In [117]:
a=torch.zeros(2,2,1)
a

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [119]:
b=a.squeeze()
b

tensor([[0., 0.],
        [0., 0.]])

In [120]:
a.shape


torch.Size([2, 2, 1])

In [121]:
b.shape

torch.Size([2, 2])

In [122]:
b

tensor([[0., 0.],
        [0., 0.]])

In [123]:
import numpy as np



# Create a 2D array with a singleton dimension

data = np.array([[[1, 2, 3]]])



# Applying squeeze will remove the singleton dimension

squeezed_data = np.squeeze(data)



print(squeezed_data)  # Output: [1 2 3]



# Here, the original shape (1, 1, 3) is reduced to (3), losing the information about the first dimension


[1 2 3]


In [124]:
v=squeezed_data.reshape(-1,1)
v

array([[1],
       [2],
       [3]])

In [125]:
a=torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [126]:
a.shape

torch.Size([2, 2])

In [130]:
e=torch.unsqueeze(a,1)
e

tensor([[[0., 0.]],

        [[0., 0.]]])

In [128]:
b.shape

torch.Size([1, 2, 2])

In [131]:
e.shape

torch.Size([2, 1, 2])

In [132]:
b

tensor([[[0., 0.],
         [0., 0.]]])

In [133]:
b.shape

torch.Size([1, 2, 2])

In [135]:
b=torch.ones(3,3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [136]:
c=torch.rand(3,3)
c

tensor([[0.6975, 0.9318, 0.0335],
        [0.3115, 0.8176, 0.1296],
        [0.1569, 0.6448, 0.6024]])

In [137]:
# conducting logical operations on tensors using the any and all methods

a=torch.rand(3,3)
a



tensor([[0.6221, 0.9238, 0.7027],
        [0.3088, 0.0100, 0.1742],
        [0.3700, 0.3744, 0.2876]])

In [138]:
a.shape

torch.Size([3, 3])

In [141]:
torch.any(a>1.0)

tensor(False)

In [142]:
a=torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
b=a.view(3,3)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [144]:
b.shape

torch.Size([3, 3])

In [145]:
c=a.view(3,-1)
c

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
a.shape

torch.Size([9])

In [148]:
a=torch.rand(3,3)
a

tensor([[0.2494, 0.0079, 0.9155],
        [0.0536, 0.9460, 0.0047],
        [0.4858, 0.2263, 0.7396]])

In [150]:
b=a.flatten()
b.shape

torch.Size([9])

In [151]:
a

tensor([[0.2494, 0.0079, 0.9155],
        [0.0536, 0.9460, 0.0047],
        [0.4858, 0.2263, 0.7396]])

In [155]:
b=torch.LongTensor([[0,1,2]])
b

tensor([[0, 1, 2]])

In [156]:
b.shape

torch.Size([1, 3])

In [159]:
c=a.gather(0,b)
c

tensor([[0.2494, 0.9460, 0.7396]])

In [161]:
input_tensor=torch.zeros(3,5)
index=torch.tensor([[0,1,2,0,1],[2,0,1,1,0],[1,2,0,2,1]])
src=torch.tensor([[10,20,30,40,50],[1,2,3,4,5],[5,6,7,8,9]])

In [162]:
input_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [163]:
import torch

input_tensor = torch.zeros(3, 5)
index = torch.tensor([[0, 1, 2, 0, 1], 
                      [2, 0, 1, 1, 0], 
                      [1, 2, 0, 2, 1]])
src = torch.tensor([[10, 20, 30, 40, 50], 
                    [1, 2, 3, 4, 5], 
                    [5, 6, 7, 8, 9]])
output = torch.scatter(input_tensor, 1, index, src)
print(output)


RuntimeError: scatter(): Expected self.dtype to be equal to src.dtype

In [167]:
import pandas as pd
import numpy as np
s=pd.Series(np.random.randint(10,100,10))
print(s)

print(s.argmax())

0    79
1    49
2    46
3    42
4    94
5    14
6    53
7    15
8    24
9    59
dtype: int32
4


In [3]:
a=torch.rand(3,3)*100
a

tensor([[89.2998, 21.4766, 18.4692],
        [21.4541,  3.1712, 32.8685],
        [57.0191, 92.4284, 57.1076]])

In [4]:
b=torch.floor(a)
b



tensor([[89., 21., 18.],
        [21.,  3., 32.],
        [57., 92., 57.]])

In [5]:
c=torch.ceil(a)
c

tensor([[90., 22., 19.],
        [22.,  4., 33.],
        [58., 93., 58.]])

In [6]:
a=torch.rand(3,3)
a 

tensor([[0.4779, 0.4344, 0.2144],
        [0.8334, 0.2407, 0.6028],
        [0.7765, 0.9343, 0.1616]])

In [7]:
b=torch.FloatTensor([[0,1,0],[1,1,1],[0,1,0]])
b

tensor([[0., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])

In [8]:
c=torch.mul(a,b)
c

tensor([[0.0000, 0.4344, 0.0000],
        [0.8334, 0.2407, 0.6028],
        [0.0000, 0.9343, 0.0000]])

In [9]:
a=torch.rand(3,3)
a

tensor([[0.0718, 0.4832, 0.9794],
        [0.4560, 0.8603, 0.4723],
        [0.4615, 0.4542, 0.0455]])

In [11]:
c=torch.div(a,b)
c  





tensor([[   inf, 0.4832,    inf],
        [0.4560, 0.8603, 0.4723],
        [   inf, 0.4542,    inf]])

In [12]:
a=torch.randn(10)
a

tensor([ 0.4109,  1.2687,  1.2913, -1.0702, -0.9986, -0.7838, -0.1690,  0.5927,
        -0.2933,  0.1079])

In [13]:
a=torch.cumprod(a,dim=0)
a

tensor([ 0.4109,  0.5212,  0.6731, -0.7204,  0.7194, -0.5638,  0.0953,  0.0565,
        -0.0166, -0.0018])

In [15]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
cumulative_product = torch.cumprod(tensor, dim=1)
print(cumulative_product)

tensor([[  1,   2,   6],
        [  4,  20, 120]])


In [16]:
b=torch.FloatTensor([[0,1,0],[1,1,1],[0,1,0]])
b

tensor([[0., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])

In [17]:
a.shape

torch.Size([10])

In [19]:
b.shape

torch.Size([3, 3])

In [21]:
c=torch.mul(a,b)
c

RuntimeError: The size of tensor a (10) must match the size of tensor b (3) at non-singleton dimension 1

In [22]:
a=torch.linspace(  -1,1,10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [23]:
torch.sin(a)

tensor([-0.8415, -0.7017, -0.5274, -0.3272, -0.1109,  0.1109,  0.3272,  0.5274,
         0.7017,  0.8415])

In [30]:
p=torch.sin(torch.tensor(-1.0))
p

tensor(-0.8415)

In [31]:
torch.tan(torch.tensor(-1))

tensor(-1.5574)

In [32]:
b=torch.rand(3,3)
b

tensor([[0.4691, 0.7452, 0.1099],
        [0.9957, 0.1326, 0.6834],
        [0.2984, 0.4698, 0.5427]])

In [34]:
a=torch.ones(2,3)
a.shape

torch.Size([2, 3])

In [35]:
b=torch.ones(3,3)   
b.shape

torch.Size([3, 3])

In [36]:
a=torch.ones(2,3,2)
a

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [37]:
b=torch.ones(2,3,2)
b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [39]:
a=torch.ones(4)
a

tensor([1., 1., 1., 1.])

In [40]:
a=torch.norm(a,1)
a

tensor(4.)

In [42]:
import torch
tensor=torch.tensor([[1,2,3],[4,5,6]])

tensor_new=tensor.view(3,2)
tensor_new

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [43]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor.size())

torch.Size([2, 3])


In [44]:
tensor=torch.tensor([42.0])
value=tensor.item()
print(value)

42.0


In [45]:
tensor=torch.tensor([[[1,2,3]]])
squeezed=tensor.squeeze()
print(tensor.shape)
print(squeezed.shape)

torch.Size([1, 1, 3])
torch.Size([3])


In [49]:
tensor1=torch.tensor([[1,2],[3,4]])
tensor2=torch.tensor([[5,6],[7,8]])

concat_dim0=torch.cat((tensor1,tensor2),dim=0)

concat_dim0

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [48]:
tensor1.shape

torch.Size([2, 2])

In [50]:
import torch

# Create a tensor of size (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape it to (3, 2)
reshaped = tensor.view(3, 2)
print("Original Tensor:\n", tensor)
print("Reshaped Tensor:\n", reshaped)

Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped Tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [51]:
# Create a tensor with extra dimensions
tensor = torch.tensor([[[1, 2, 3]]])

# Remove dimensions of size 1
squeezed = tensor.squeeze()
print("Original Tensor:", tensor.shape)
print("Squeezed Tensor:", squeezed.shape)


Original Tensor: torch.Size([1, 1, 3])
Squeezed Tensor: torch.Size([3])
